#!/usr/bin/env python3
"""Is the live site actually serving main?

The Cloudflare Pages Git integration once stopped deploying for three days
with no error anywhere, and when it was reconnected the first build failed
on a typo. Both times the dashboard looked fine and the site was stale.
This reads the public site, needs no Cloudflare credentials, and compares
key files byte for byte against the repo.

    python3 tools/check_live.py            # from the repo root, full history

Outcomes (also written to $GITHUB_OUTPUT as outcome=…):
  ok            every file that answered matches main
  diverged      at least one file answered and does not match main   → exit 1
  inconclusive  nothing answered usably (403/503, bot challenge, network)

A 404 counts as diverged, not inconclusive. Bot management challenges or
refuses; it does not answer "not found". A 404 on a file main has means
the deploy is missing it, which is exactly the failure this exists for.

A commit younger than GRACE_MINUTES may still be building, so a file
matching either main's tip or the newest commit older than that passes.
"""
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

HOSTS = ["venice.primalmoves.com", "primalmovesweb.pages.dev"]
GRACE_MINUTES = 20
UA = ("Mozilla/5.0 (compatible; primalmoves-live-check; "
      "+https://github.com/giddyuptiger/primalmovesweb)")

# (url path, repo path). Pages are generated by tools/build_d9.py, the rest are
# hand-authored or written by the refresh Action, so between them a stale
# build, a partial build and a missing assets/ copy all show up.
CHECKS = [
    ("/", "design-9/index.html"),
    ("/studio/", "design-9/studio/index.html"),
    ("/classes/", "design-9/classes/index.html"),
    ("/memberships/", "design-9/memberships/index.html"),
    ("/visit/", "design-9/visit/index.html"),
    ("/style.css", "design-9/style.css"),
    ("/config.js", "design-9/config.js"),
    ("/schedule.json", "design-9/schedule.json"),
]


def git(*args):
    return subprocess.run(["git", *args], check=True, capture_output=True).stdout


def main_ref():
    """A scheduled checkout may only have origin/main."""
    for ref in ("main", "origin/main"):
        if subprocess.run(["git", "rev-parse", "--verify", "-q", ref],
                          capture_output=True).returncode == 0:
            return ref
    sys.exit("no main branch in this checkout")


MAIN = None


def newest_asset():
    """The file most recently added under assets/. Only reaches the site
    through the `cp -r assets design-9/` build step."""
    out = git("log", "--diff-filter=A", "--name-only", "--format=", "-n", "20",
              MAIN, "--", "assets/").decode().split("\n")
    for path in out:
        if path and git("cat-file", "-t", f"{MAIN}:{path}").strip() == b"blob":
            return ("/" + urllib.parse.quote(path), path)
    return None


def settled_commit():
    """Newest commit on main old enough that its build should have finished."""
    cutoff = int(time.time()) - GRACE_MINUTES * 60
    for line in git("log", "--format=%H %ct", "-n", "50", MAIN).decode().split("\n"):
        if line:
            sha, ts = line.split()
            if int(ts) <= cutoff:
                return sha
    return None


def blob(rev, path):
    try:
        return git("show", f"{rev}:{path}")
    except subprocess.CalledProcessError:
        return None


# Cloudflare zone features on the custom domain can rewrite HTML on the way
# out. Undo the known ones so a rewrite is not reported as a stale deploy.
CFEMAIL_SPAN = re.compile(
    rb'<(?:span|a)[^>]*class="__cf_email__"[^>]*data-cfemail="([0-9a-f]+)"[^>]*>'
    rb'\[email&#160;protected\]</(?:span|a)>')
CFEMAIL_HREF = re.compile(rb'/cdn-cgi/l/email-protection#([0-9a-f]+)')
CF_SCRIPT = re.compile(
    rb'<script[^>]*(?:/cdn-cgi/|cloudflareinsights\.com)[^>]*>\s*</script>')


def decode_cfemail(hexstr):
    b = bytes.fromhex(hexstr.decode())
    return bytes(c ^ b[0] for c in b[1:])


def undo_cloudflare(body):
    body = CFEMAIL_SPAN.sub(lambda m: decode_cfemail(m.group(1)), body)
    body = CFEMAIL_HREF.sub(lambda m: b"mailto:" + decode_cfemail(m.group(1)), body)
    return CF_SCRIPT.sub(b"", body)


def fetch(host, path):
    """→ (status, body or None, note)."""
    url = f"https://{host}{path}"
    req = urllib.request.Request(url, headers={
        "User-Agent": UA, "Cache-Control": "no-cache", "Pragma": "no-cache"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = r.read()
            if r.headers.get("cf-mitigated") == "challenge" or \
                    b"<title>Just a moment...</title>" in body[:4000]:
                return r.status, None, "bot challenge"
            return r.status, body, ""
    except urllib.error.HTTPError as e:
        return e.code, None, ""
    except Exception as e:  # DNS, TLS, timeout: our network, not the site
        return 0, None, type(e).__name__


def where_from(body, path):
    """The newest commit whose copy of this file is exactly what live serves,
    to say how stale live is."""
    sha = subprocess.run(["git", "hash-object", "--stdin"], input=body,
                         capture_output=True, check=True).stdout.decode().strip()
    for commit in git("log", "--format=%H", "-n", "300", MAIN, "--",
                      path).decode().split():
        got = subprocess.run(["git", "rev-parse", "-q", "--verify", f"{commit}:{path}"],
                             capture_output=True).stdout.decode().strip()
        if got == sha:
            later = git("log", "--format=%h", f"{commit}..{MAIN}", "--", path).decode().split()
            info = git("log", "-1", "--format=%h %cs %s", commit).decode().strip()
            return f"main as of {info} ({len(later)} change(s) since)"
    return "no recent commit on main"


def main():
    global MAIN
    MAIN = main_ref()
    head = git("rev-parse", MAIN).decode().strip()
    settled = settled_commit()
    checks = list(CHECKS)
    asset = newest_asset()
    if asset:
        checks.append(asset)

    rows, diverged, answered = [], 0, 0
    stamp = str(int(time.time()))
    for host in HOSTS:
        for url_path, repo_path in checks:
            want = {blob(head, repo_path)}
            if settled and settled != head:
                want.add(blob(settled, repo_path))
            want.discard(None)
            q = url_path if repo_path.startswith("assets/") else f"{url_path}?live-check={stamp}"
            status, body, note = fetch(host, q)
            if status == 404:
                answered += 1
                diverged += 1
                rows.append((host, url_path, "DIVERGED", "404, main has this file"))
            elif status != 200 or body is None:
                rows.append((host, url_path, "inconclusive", note or f"HTTP {status}"))
            else:
                answered += 1
                if body in want or undo_cloudflare(body) in want:
                    rows.append((host, url_path, "ok", ""))
                else:
                    diverged += 1
                    rows.append((host, url_path, "DIVERGED",
                                 "live matches " + where_from(body, repo_path)))

    outcome = "diverged" if diverged else ("ok" if answered else "inconclusive")
    head_line = git("log", "-1", "--format=%h %cs %s", head).decode().strip()

    lines = [f"## Live site vs main: **{outcome}**", "",
             f"main is `{head_line}`", "",
             "| host | path | result | detail |", "|---|---|---|---|"]
    lines += [f"| {h} | `{p}` | {r} | {d} |" for h, p, r, d in rows]
    report = "\n".join(lines) + "\n"
    print(report)

    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as f:
            f.write(report)
    if os.environ.get("GITHUB_OUTPUT"):
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"outcome={outcome}\n")
    if outcome == "inconclusive":
        print("::warning::live check inconclusive: no host gave a usable answer")
    if outcome == "diverged":
        print(f"::error::live site does not match main ({diverged} file(s))")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
